/**
 * This code was generated by the Kepler Codegen tool.
 *
 * It is provided as a starting template and can be modified.
 *
 * @generated by GenerateModuleH.js
 */

#pragma once

#include "generated/TailscaleSpec.h"
#include "tailscale.h"

#include <memory>
#include <mutex>
#include <string>

namespace tailvega {

struct EngineState {
  std::mutex mutex;
  tailscale server{-1};
  std::string proxyAddress;
  std::string proxyCredential;
};

class Tailscale : public TailscaleSpec {
public:
  Tailscale();
  ~Tailscale() noexcept;

  com::amazon::kepler::turbomodule::Promise connect(std::string authKey, std::string hostname) override;
  com::amazon::kepler::turbomodule::Promise status() override;
  com::amazon::kepler::turbomodule::Promise disconnect() override;
  com::amazon::kepler::turbomodule::Promise probe(std::string address) override;
  std::string engineVersion() override;

private:
  std::shared_ptr<EngineState> state_;
};

} // namespace tailvega
